Milestone 1-6: Bootstrap
Leandro-Barretoo/project3-bootstrap pull request #1
Opened 2020-12-09 14:53 UTC by jebitok-dev

### Newsweek Replica Milestones:

In these milestones we:
- Set up the repository and prepared assets for our website.
- Analyzed different parts of the website and created the skeleton
- Applied styles and positioning using bootstrap classes 
- Used Bootstrap classes to create different viewports of the website.

2020-12-09 17:43 UTC, mimipeshy commented
## STATUS:  CHANGES REQUIRED 🔴 ♻️ 
Hello team @jebitok-dev  and @Leandro-Barretoo  👋 👋 , good job on the project so ar, it looks good but let's make it better 😄

#### Large view
- [ ]  The navigation bar should resemble the original one [link to page](https://www.newsweek.com/)
Original
![o](https://user-images.githubusercontent.com/33067256/101663299-96b7e080-3a5b-11eb-9b5c-2b5d6a06d310.PNG)


Clone
![c](https://user-images.githubusercontent.com/33067256/101663219-7a1ba880-3a5b-11eb-9137-8e33697f3ae1.PNG)

#### Medium view

- [ ]  The navigation bar should resemble the original one [link to page](https://www.newsweek.com/)

Original
![o](https://user-images.githubusercontent.com/33067256/101663603-f6ae8700-3a5b-11eb-911c-5b131de09d5d.PNG)

Clone
![c](https://user-images.githubusercontent.com/33067256/101663631-0037ef00-3a5c-11eb-8a7f-b3f71a4af221.PNG)

- [ ]  Ensure the whole page looks exactly like the original one [link to page](https://www.newsweek.com/)
Original


Clone
![or](https://user-images.githubusercontent.com/33067256/101664347-c9aea400-3a5c-11eb-8d57-5abecf751235.PNG)


- [ ]  Give margins between the articles in the world, business, tech & science, sports, and US section [link to page](https://www.newsweek.com/)

Original

![or](https://user-images.githubusercontent.com/33067256/101664486-f5318e80-3a5c-11eb-9f7a-6efdcf5d0a3e.PNG)

Clone
![c](https://user-images.githubusercontent.com/33067256/101664025-6de41b00-3a5c-11eb-8b11-29a55115ffc5.PNG)

- [ ] One image is missing in the subscribe section. Kindly add it and align as it looks in the original page. [link to page](https://www.newsweek.com/)
Original
![sub](https://user-images.githubusercontent.com/33067256/101664736-3fb30b00-3a5d-11eb-802e-d6b8f34f0929.PNG)

Clone
![c](https://user-images.githubusercontent.com/33067256/101664760-46da1900-3a5d-11eb-9a1f-6d82364557ae.PNG)

#### Mobile view

- [ ]  Top story should be the first article in this view [link to page](https://www.newsweek.com/)

- [ ] Navigation bar should resemble  the original one [link to page](https://www.newsweek.com/)

Original
![or](https://user-images.githubusercontent.com/33067256/101665422-0202b200-3a5e-11eb-8416-fceab1f631fe.PNG)

Clone
![c](https://user-images.githubusercontent.com/33067256/101665355-f1523c00-3a5d-11eb-9e9d-314ad69d38ce.PNG)

- [ ] Ensure the in magazine section looks like the original one  [link to page](https://www.newsweek.com/)

Original
![image](https://user-images.githubusercontent.com/33067256/101665922-a4229a00-3a5e-11eb-86c4-6eff33891e49.png)


Clone
![image](https://user-images.githubusercontent.com/33067256/101665740-6d4c8400-3a5e-11eb-9b6e-4dff62ca17b4.png)

- [ ]  Editor's pick should look like the original one

Original
![image](https://user-images.githubusercontent.com/33067256/101666198-f663bb00-3a5e-11eb-8331-240639647a3a.png)


Clone
![image](https://user-images.githubusercontent.com/33067256/101666108-da601980-3a5e-11eb-8ce8-645e4ec0d860.png)


- [ ] Take a minute to ensure the whole page looks like the original one  [link to page](https://www.newsweek.com/)

- [ ] Remove the commented code in your HTML file


That's all. 😄 , kindy submit another review when you are done

Regards
Peris Ndanu
Feel free to reach out on slack if you have any questions

2020-12-11 19:30 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @wrakc** 
Good job with your first submission for this project :muscle:  :muscle:
Your page meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] Your footer only have 4 of 5 social media icons from the original, add the Instagram icon
- [ ] The page should use two break points (like the original) and not only one

| Yours | Original |
|:---:|:---:|
|![image](https://i.imgur.com/ol2vcqA.png) | ![image](https://i.imgur.com/k2RJ7CZ.png) |

- [ ] Group selectors with the same style definition
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2020-12-11 19:30 UTC, andresporras3423 commented on stylesheets/app.css
> +}
Same style definition of the selector on line 67, group selectors with the same style definition

2020-12-12 01:31 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] The github actions linter configuration is not correct, the linters are not running, please fix this.
![image](https://user-images.githubusercontent.com/25774518/101969004-ae23d480-3be7-11eb-80fb-aa14ee6b9d4f.png)


- [ ] The branch has some issues please fix them
![image](https://user-images.githubusercontent.com/25774518/101968983-92203300-3be7-11eb-9fc2-dc447766fe3a.png)

- [ ] The website is non-responsive. See notes below:

> * [x]  Your footer only have 4 of 5 social media icons from the original, add the Instagram icon 
- [ ]  The page should use two breakpoints (like the original) and not only one. **The project has two break points to give you a hint they are 768px and 425px** 

These breakpoints go like this:
Desktop above 769px;
Tablet view between 768px to 426px;
Mobile view below 425px;

This means that the project should have 3 views, Desktop, Tablet, and Mobile.

Right now the project has a mixture of Tablet and Mobile and is making the Desktop view.

Example:
#### Original

| Desktop | Tablet | Mobile |
| - | - | - |
| ![image](https://user-images.githubusercontent.com/25774518/101968684-f9d57e80-3be5-11eb-9a14-a2d5ba7a4069.png) | ![image](https://user-images.githubusercontent.com/25774518/101968707-0fe33f00-3be6-11eb-9630-a27312d87ca4.png) | ![image](https://user-images.githubusercontent.com/25774518/101968720-1d98c480-3be6-11eb-9fda-475cef636f82.png) |

#### Clone

| Desktop | Tablet | Mobile |
| - | - | - |
| ![image](https://user-images.githubusercontent.com/25774518/101968752-4a4cdc00-3be6-11eb-953e-6b2dbc9144f8.png) | ![image](https://user-images.githubusercontent.com/25774518/101968762-5f296f80-3be6-11eb-9d8c-2c550e477227.png) | ![image](https://user-images.githubusercontent.com/25774518/101968769-6cdef500-3be6-11eb-8396-ed9dbaeade58.png) |

- [ ]  Group selectors with the same style definition. **The stylesheet still has repeated CSS rules, keep the code DRY and join them together**

 Example:
```css
# Bad CSS
.element__one {
  color: red;
}

.element__two {
  color: red;
}

/* Good CSS option 1 */

.element__one,
.element__two {
  color: red;
}

/* Good CSS option 2 */

.color-red {
  color: red;
}
```

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-12-12 06:23 UTC, mimipeshy commented
## STATUS: CHANGES REQUIRED 🔴 ♻️ 

Hello team @jebitok-dev and @Leandro-Barretoo  👋 👋 
✔️  Good job on working on the TSE feedback you were given
✔️ Your project is now taking shape, its almost resembling the original page
⚠️ Don't give up yet because of all the changes you are being told to make, we want you to be the best developers

Let's make a few more changes before we mark the project as `complete`
**Note**: use bootstrap classes to achieve the changes, using CSS styles is okay but will take you more time to make all the changes that could easily solved with a simple bootstrap class

### MANDATORY 🔴 

- [ ]  The whole project is missing the tablet breakpoint which is 768px. Kindy fix that . `col-md` is used in this breakpoint. Since this project is bootstrap-based, you should make use of bootstrap classes to order and align elements instead of CSS.

- [ ] In the debate section you are missing the `vs` icon just between the two articles

Original | Clone
------------ | -------------
![image](https://user-images.githubusercontent.com/33067256/101976655-7608aa00-3c58-11eb-81dc-3a00a8de8220.png) |![image](https://user-images.githubusercontent.com/33067256/101976699-efa09800-3c58-11eb-83b4-3e9614d251ad.png)


Notice the difference ❓ ❓ 

- [ ] On tablet view, the `IN THE MAGAZINE ` section should be aligned to 4 articles per row. Use bootstrap classes to achieve this rather than writing CSS styles.

- [ ] On a tablet view, the `Editor's Picks` section should be aligned with two articles per row. Use bootstrap classes to achieve this.

- [ ] On the tablet view, this section is missing. Add it
![image](https://user-images.githubusercontent.com/33067256/101976823-2aef9680-3c5a-11eb-98bf-e87dbc71d8d6.png)


- [ ] On the desktop view, there are issues with alignment in the `IN THE MAGAZINE` section. Kindly fix that

Original | Clone
------------ | -------------
![image](https://user-images.githubusercontent.com/33067256/101976785-c16f8800-3c59-11eb-8371-1031b95ea930.png) |![image](https://user-images.githubusercontent.com/33067256/101976772-95540700-3c59-11eb-8f6c-3132b95acbed.png)

Notice the difference ❓ ❓ 

- [ ] On desktop view the `editors section` also has alignment issues

Original | Clone
------------ | -------------
![image](https://user-images.githubusercontent.com/33067256/101976974-5b840000-3c5b-11eb-8e61-541863db5efb.png) |![image](https://user-images.githubusercontent.com/33067256/101976947-2f687f00-3c5b-11eb-80ae-6ea73295003c.png)

Notice the difference ❓ ❓ 

- [ ] On the desktop view, this section is missin too. Add it
![image](https://user-images.githubusercontent.com/33067256/101976835-4a86bf00-3c5a-11eb-87c5-31b16b8f2227.png)

- [ ] This section `US, WOLRD, POLITICS` etc too needs margins between each article
![image](https://user-images.githubusercontent.com/33067256/101976851-786c0380-3c5a-11eb-82d9-1edee0d26171.png)

- [ ] The buttons on the `subscribe` and `newsletter` section are flowing out of the container. Kindly fix that
![image](https://user-images.githubusercontent.com/33067256/101976924-047e2b00-3c5b-11eb-9e2e-5d05dd0c716a.png)


That's all 😄 kindly submit another review when you are done.

Regards
Peris Ndanu
Feel free to slack me anytime if you have any questions.

2020-12-12 17:58 UTC, mimipeshy commented
## STATUS :  CHANGES REQUESTED 🔴 ♻️ 

Hey team 👋 👋 it's me again 😄 
✔️ Great job on working on the requirements above, your project is looking really good.

However, before we approve it lets fix one more thing

- [ ] On mobile and tablet view, the contents below editor's section and above the subscribe section, should be hidden.

That's all. 😄 , kindy submit another review when you are done

Regards
Peris Ndanu
Feel free to reach out on slack if you have any questions

2020-12-12 20:48 UTC, mimipeshy commented
## STATUS : APPROVED 🥳 🍾 

Hey team @jebitok-dev and @Leandro-Barretoo, I mark this project as approved. You have met all requirements needed. Go ahead and merge. 

All the best in future projects. happy coding 💻 


Regards
Peris Ndanu

2020-12-12 20:58 UTC, merged